clean: bytes = (
    b"Title:           \n"
    b"Subject:         \n"
    b"Keywords:        \n"
    b"Author:          \n"
    b"Creator:         LaTeX via pandoc\n"
    b"Producer:        pdfTeX-1.40.24\n"
    b"CreationDate:    Sat Aug 27 21:28:45 2022 CEST\n"
    b"ModDate:         Sat Aug 27 21:28:45 2022 CEST\n"
    b"Custom Metadata: yes\n"
    b"Metadata Stream: no\n"
    b"Tagged:          no\n"
    b"UserProperties:  no\n"
    b"Suspects:        no\n"
    b"Form:            none\n"
    b"JavaScript:      no\n"
    b"Pages:           1\n"
    b"Encrypted:       no\n"
    b"Page size:       612 x 792 pts (letter)\n"
    b"Page rot:        0\n"
    b"File size:       53029 bytes\n"
    b"Optimized:       no\n"
    b"PDF version:     1.5\n"
)

owner_encrypted: bytes = (
    b"Title:           \n"
    b"Subject:         \n"
    b"Keywords:        \n"
    b"Author:          \n"
    b"Creator:         LaTeX via pandoc\n"
    b"Producer:        pdfTeX-1.40.24\n"
    b"CreationDate:    Sat Aug 27 21:28:45 2022 CEST\n"
    b"ModDate:         Sat Aug 27 21:28:45 2022 CEST\n"
    b"Custom Metadata: yes\n"
    b"Metadata Stream: no\n"
    b"Tagged:          no\n"
    b"UserProperties:  no\n"
    b"Suspects:        no\n"
    b"Form:            none\n"
    b"JavaScript:      no\n"
    b"Pages:           1\n"
    b"Encrypted:       yes (print:yes copy:yes change:yes addNotes:yes algorithm:RC4)\n"
    b"Page size:       612 x 792 pts (letter)\n"
    b"Page rot:        0\n"
    b"File size:       53428 bytes\n"
    b"Optimized:       no\n"
    b"PDF version:     1.5\n"
)
